[[redirects]]
  from = "/"
  to = "/.netlify/functions/get_click"
  status = 200
[build]
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
[build]
  functions = "functions"

[functions]
  node_bundler = "esbuild"
