# Konfigurasi Build
[build]
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"

# Konfigurasi Functions
[functions]
  node_bundler = "esbuild"

# Redirect hanya untuk API Functions, bukan untuk seluruh halaman!
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
